version: "2"
services: 
    postgres:
        image: postgres:9.6.3
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./sql/sourceTables.sql:/docker-entrypoint-initdb.d/sourceTables.sql
        ports:
            - "5432:5432"